### PR TITLE
added dGen.md with data descriptions

### PR DESCRIPTION
**Pull request by T-Man-Stan**
Added descriptions of data along with CLI args for restoring the data. Linked to the open source dGen repo where further documentation and code examples can be found.

### CODE REVIEW

**Review by dstright — COMMENTED** [review]
Thanks for creating the documentation Trevor. Would it be helpful to add a link to publications here? Also, another link to, and description of the data dictionary? Do you want to include the data license here as well?

**Comment by T-Man-Stan** [comment]
Hey Dana, 

I just updated the .md file with the information you mentioned (excluding the data dictionary as this will be in the submission as well as in the dgen wiki). Please LMK if you need anything else on my end.

Thanks, 
Trevor

**Review by dstright — APPROVED** [review]

**Review by dstright — APPROVED** [review]

**Review by dstright — APPROVED** [review]

**Comment by dstright** [comment]
Hi Trevor. Looks good, thanks!

**Comment by dstright** [comment]
Trevor and David, are we ok to merge?

**Pull request merged**
