### PR TITLE
Create DarkFiber.md

### PR DESCRIPTION
**Pull request by alowney**

### CODE REVIEW

**Review by ntaverna — CHANGES_REQUESTED** [review]
In Directory Structure section, state that fiels are ~400 MB each and explain naming scheme (I think it is DF__UTC_YYYYMMDD_HHMMSS.602.h5, where the time is probably start time? I'd double check start or end time).

In Data Format section, it would be nice to define the arrays stored in each hdf5 file. Scott is working on a DAS data pipeline and may have some insight here if array labels are unclear.

Change this link: https://www.osti.gov/pages/biblio/1903439 too an actual citation.

Otherwise looks good!

**Review by jgu2 — APPROVED** [review]
It looks good, thanks for update!

**Comment by jgu2** [comment]
Oops, I mean to approve a PR from other one related to NSO. Forget my approval on this PR.

**Review by ntaverna — APPROVED** [review]
Looks good! Thanks Adrienne

**Pull request merged**
